Install KSO in the container

diff --git a/containers/final/Dockerfile b/containers/final/Dockerfile
--- a/containers/final/Dockerfile
+++ b/containers/final/Dockerfile
@@ -18,6 +18,26 @@ RUN adduser --disabled-password \
 COPY --chown=${NB_UID}:${NB_UID} . /opt/kso
 RUN chmod +x /opt/kso/containers/entrypoint.sh
 
+# Install KSO (all dependencies should be satisfied already)
+ARG PIP_BREAK_SYSTEM_PACKAGES=1
+ARG PIP_ROOT_USER_ACTION=ignore
+ARG PIP_NO_CACHE_DIR=1
+RUN pip install --no-deps /opt/kso[dev]
+
+# Check that all dependencies are satisfied
+RUN pip check || { \
+    echo ""; \
+    echo "ERROR: Installed dependencies failed validation."; \
+    echo ""; \
+    echo "This means that requirements.txt used for containers is inconsistent with pyproject.toml."; \
+    echo ""; \
+    echo "If you changed dependencies in pyproject.toml, update requirements.txt too."; \
+    echo ""; \
+    echo "Dependency issues reported by 'pip check':"; \
+    pip check; \
+    exit 1; \
+}
+
 # Set run environment
 USER ${NB_USER}
 WORKDIR /opt/kso
